import { NextRequest, NextResponse } from "next/server";
import { randomBytes } from "node:crypto";
import { apiError, currentUser } from "@/lib/api/auth";
import { encryptSecret } from "@/lib/security/crypto";
import { safeShopDomain, verifyShopifyHmac } from "@/lib/security/shopify";
import { createAdminClient } from "@/lib/supabase/admin";
import { serverEnv } from "@/lib/env";
import { registerShopifyWebhooks } from "@/services/shopify/client";
export async function GET(request: NextRequest) { try {
  const { user } = await currentUser(); const params = request.nextUrl.searchParams;
  if (params.get("state") !== request.cookies.get("shopify_oauth_state")?.value || !verifyShopifyHmac(params)) return NextResponse.json({ error: "Invalid Shopify installation request" }, { status: 400 });
  const shopDomain = safeShopDomain(params.get("shop") || ""); const code = params.get("code"); if (!code) return NextResponse.json({ error: "Missing Shopify authorization code" }, { status: 400 }); const env = serverEnv();
  const tokenResponse = await fetch(`https://${shopDomain}/admin/oauth/access_token`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ client_id: env.SHOPIFY_CLIENT_ID, client_secret: env.SHOPIFY_CLIENT_SECRET, code }), signal: AbortSignal.timeout(15_000) });
  const tokenResult = await tokenResponse.json() as { access_token?: string; scope?: string }; if (!tokenResponse.ok || !tokenResult.access_token) throw new Error("Shopify did not return an access token");
  const shopResponse = await fetch(`https://${shopDomain}/admin/api/${env.SHOPIFY_API_VERSION}/graphql.json`, { method: "POST", headers: { "Content-Type": "application/json", "X-Shopify-Access-Token": tokenResult.access_token }, body: JSON.stringify({ query: "{ shop { id name currencyCode ianaTimezone } }" }) }); const shopPayload = await shopResponse.json() as { data?: { shop?: { id: string; name: string; currencyCode: string; ianaTimezone: string } } }; const remoteShop = shopPayload.data?.shop; if (!remoteShop) throw new Error("Unable to identify Shopify store");
  const admin = createAdminClient(); const { data: existing } = await admin.from("shops").select("id,organization_id").eq("shop_domain", shopDomain).maybeSingle(); let shopId: string;
  if (existing) { const { data: membership } = await admin.from("memberships").select("id").eq("organization_id", existing.organization_id).eq("user_id", user.id).maybeSingle(); if (!membership) return NextResponse.json({ error: "You are not authorized to reconnect this store." }, { status: 403 }); shopId = existing.id; await admin.from("shops").update({ name: remoteShop.name, currency: remoteShop.currencyCode, timezone: remoteShop.ianaTimezone || "Asia/Dhaka", connection_status: "healthy" }).eq("id", shopId); }
  else { const slug = `${remoteShop.name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"").slice(0,45) || "shop"}-${randomBytes(3).toString("hex")}`; const { data: org, error: orgError } = await admin.from("organizations").insert({ name: remoteShop.name, slug }).select().single(); if (orgError || !org) throw orgError || new Error("Unable to create organization"); await admin.from("memberships").insert({ organization_id: org.id, user_id: user.id, role: "owner" }); const { data: created, error: createError } = await admin.from("shops").insert({ organization_id: org.id, shop_domain: shopDomain, shopify_shop_gid: remoteShop.id, name: remoteShop.name, currency: remoteShop.currencyCode, timezone: remoteShop.ianaTimezone || "Asia/Dhaka", connection_status: "healthy" }).select().single(); if (createError || !created) throw createError || new Error("Unable to create store"); shopId = created.id; }
  const encrypted = encryptSecret({ accessToken: tokenResult.access_token }); await admin.from("shopify_installations").upsert({ shop_id: shopId, access_token_ciphertext: encrypted.ciphertext, access_token_iv: encrypted.iv, access_token_tag: encrypted.authTag, scopes: (tokenResult.scope || "").split(",").filter(Boolean), revoked_at: null });
  await registerShopifyWebhooks(shopId); await admin.from("sync_jobs").insert({ shop_id: shopId, kind: "initial", created_by: user.id }); await admin.from("audit_logs").insert({ organization_id: existing?.organization_id || (await admin.from("shops").select("organization_id").eq("id", shopId).single()).data!.organization_id, shop_id: shopId, actor_id: user.id, action: "shopify.connected", entity_type: "shop", entity_id: shopId });
  const response = NextResponse.redirect(new URL(`/orders?shop=${shopId}`, env.SHOPIFY_APP_URL)); response.cookies.delete("shopify_oauth_state"); return response;
} catch (error) { return apiError(error); } }
